### ISSUE TITLE
Add element-style margin-right: 15px to tag <body>?!

### ISSUE THREAD

**Issue by grandemeister** [vova07/yii2-imperavi-widget#34]
Hi, Vova! Tnx for your nice job!
I have the next problem: connected redactor - that's ok, but when i clicked the buttons "link" and "alignment", and moving mouse-point over the dropdown-menu, all page-content "shifts" or "rides" to the left-side.
I saw the source-code - there exactly at this moment added to tag body css "style="margin-right:15px". Perhaps to fix it somehow?

**Comment by grandemeister** [comment]
Upd.: hmm... i tryed to find this on the page imperavi.com/redactor/examples/dropdown/ - exacltly added margin, but content doesn't "shift" to the left. I don't understand... :(

**Comment by vova07** [comment]
Hi @grandemeister,
Sorry for late answer.
I think the problem is somewhere in your `CSS` styles. Maybe you have some conflicts, because I can't reproduce this bug on my local system.
Try please to reproduce this bug, on clean app with default `HTML` template. If on the clean template all will work like it is expected then the problem is for sure in your `CSS`.

**Comment by grandemeister** [comment]
Thank you for the response!
This problem isn't your widget ... i'm sorry) I could repeat this case on the http://imperavi.com/redactor/ )))
I'll write to the developers of redactor about this.

Best regards!
