### ISSUE TITLE
Generate thumbnails for uploaded images

### ISSUE THREAD

**Issue by jShox** [vova07/yii2-imperavi-widget#51]
Imagemanager supports to send thumbs pathes. Why didn't use it?
It is not so hard to resize images.
Additional path for thumbs could be setuped in the 'images-get' action.
Or maybe just add suffix '_thumb' and put them in the same directory with original images.
Also is good idea to setup max size of original images and resize them too.

**Comment by vova07** [comment]
Hi, it's a really old response, but today I've google a bit about thumbs in redactor 10, and unfortunately didn't get any result.
If there is still a link about that functionality will be nice to read it.

Because of really old issue, I'll close it, but fell are to re-open it in case you have additional info.
Thanks!
