### ISSUE TITLE
Расширяемость UploadAction

### ISSUE THREAD

**Issue by ashatrov** [vova07/yii2-imperavi-widget#64]
1) Хочу писать в базу информацию о файле: новое имя, размер файла, путь к нему и т.п.
2) Сохранять файлы в разные папки /md5{2}/md5{2,2}/filename и т.п.
Для этого мне надо расширить yii2-imperavi-widget/src/actions/UploadAction.php

Из за того, что там всё в одном методе run(), я не могу достать $model для получения информации о файле. Я не могу добавить логику формирования $this->path, т.к. нет для него геттера, который можно было-бы переопределить.

**Comment by ashatrov** [comment]
То же самое с getName().
Нет возможности поменять логику генерации имени файла.

**Comment by Belotur** [comment]
А такой вариант не поможет: backend/actions/WswUploadAction.php
Я отнаследовался от экшена и использовал свой экшен в контроллере для определения кто будет загружать картинки. Решились 2 задачи: 1) именование файлов должно быть транслитом и, при этом, с уникальными названиями; 2) пользователи бездумно загружают большие картинки, но есть принцип юзабилити "Не заставляй меня думать" - добавил пропорциональный ресайз с максимальным размером большей стороны 600px (const MAX_SIDE_LENGTH = 600;).
Без ресайза экшен гораздо компактнее :-).

`<?php`
`namespace backend\actions;`
` `
`use Imagine\Image\Box;`
`use yii\imagine\Image;`
`use yii\base\DynamicModel;`
`use yii\base\Exception;`
`use yii\web\BadRequestHttpException;`
`use yii\web\Response;`
`use yii\web\UploadedFile;`
`use Yii;`
`use vova07\imperavi\actions\UploadAction;`
`use dosamigos\transliterator\TransliteratorHelper;`
` `
`/**`
` * Действие загрузки изображения для WYSIWYG-редактора.`
` * Переопределяет vova07\imperavi\actions\UploadAction в части формирования наименования файла`
` * и создания ресайза изображения.`
` *`
` * @author Belotur`
` * @since 02.08.2016`
` * @package backend\actions`
` */`
`class WswUploadAction extends UploadAction {`
`	protected $_validator = 'image';`
` `
`	const MAX_SIDE_LENGTH = 600;`
` `
`	/**`
`	 * @inheritdoc`
`	 */`
`	public function run()`
`	{`
`		if (Yii::$app->request->isPost) {`
`			$file = UploadedFile::getInstanceByName($this->uploadParam);`
`			$model = new DynamicModel(compact('file'));`
`			$model->addRule('file', $this->_validator, $this->validatorOptions)->validate();`
` `
`			if ($model->hasErrors()) {`
`				$result = [`
`					'error' => $model->getFirstError('file')`
`				];`
`			} else {`
`				if ($this->unique === true && $model->file->extension) {`
`					$model->file->name = $this->generateFileName($model->file);`
`				}`
`				try {`
`					$result = $this->saveImage($model);`
`				} catch (\Exception $e) {`
`					$result = [`
`						'error' => $e->getMessage()`
`					];`
`				}`
`			}`
`			Yii::$app->response->format = Response::FORMAT_JSON;`
` `
`			return $result;`
`		} else {`
`			throw new BadRequestHttpException('Only POST is allowed');`
`		}`
`	}`
` `
`	/**`
`	 * Генерация имени файла`
`	 * @param UploadedFile $file объект файла`
`	 *`
`	 * @return string`
`	 */`
`	protected function generateFileName($file)`
`	{`
`		$name = str_replace('.'.$file->extension, '', $file->name);`
`		$name = preg_replace('/(\d+)/m', '', $name);`
`		$name = TransliteratorHelper::process($name, '?', 'en').'-'.time();`
`		return $name . '.' . $file->extension;`
`	}`
` `
`	/**`
`	 * Сохранение изображение с пропорциональным изменением размера`
`	 * @param DynamicModel $model динамическая модель`
`	 *`
`	 * @return array`
`	 * @throws Exception`
`	 */`
`	protected function saveImage(DynamicModel $model) {`
` `
`		try {`
`			$image = Image::getImagine()->open(Yii::getAlias($model->file->tempName));`
`			$image_size = $image->getSize();`
` `
`			if ($image_size->getWidth() < $image_size->getHeight()) {// вертикальная ориентация`
`				$ratio = $image_size->getHeight()/self::MAX_SIDE_LENGTH;`
`				$width = round($image_size->getWidth() / $ratio);`
`				$height = self::MAX_SIDE_LENGTH;`
`			} else {// горизонтальная ориентация`
`				$ratio = $image_size->getWidth()/self::MAX_SIDE_LENGTH;`
`				$width = self::MAX_SIDE_LENGTH;`
`				$height = round($image_size->getHeight() / $ratio);`
`			}`
` `
`			$image->thumbnail(new Box($width, $height))->save($this->path . $model->file->name);`
` `
`			$result = ['filelink' => $this->url . $model->file->name];`
`			if ($this->uploadOnlyImage !== true) {`
`				$result['filename'] = $model->file->name;`
`			}`
`		} catch (\Exception $e) {`
`			throw new Exception(Yii::t('vova07/imperavi', 'ERROR_CAN_NOT_UPLOAD_FILE') . $e->getMessage());`
`		}`
` `
`		return $result;`
`	}`
`}`
